### ISSUE TITLE
Why not webview?

### ISSUE THREAD

**Issue by HughIsaacs2** [WICG/controlled-frame#29]
I saw in the document that this is based on [the Chrome Apps WebView API](https://developer.chrome.com/docs/extensions/reference/webviewTag/), why not just stick with `<webview>` why change it to `<controlledframe>`?

I get why this isn't an `<iframe>` attribute, but I don't get why `<webview>` doesn't suffice here.

I'm sorry if this is covered anywhere, I couldn't find anything that explained why the name choice.

**Comment by DanielHerr** [comment]
Most other platforms also use the term webview: Android, Windows, Mac, iOS

**Comment by chasephillips** [comment]
Apologies for the long time it took to get back to your message and thank you for your question. WebView is typically an OS- or toolkit-level concept and we are building this using web concepts which use different naming approaches from those OS and toolkit concepts.

In the web platform, the kind of interface that allows embedding web content in another web page is referred to as a "frame." Examples of this usage are "iframe" (inline frame), "fenced frame," and "sandboxed iframe." We want the semantics of frames (in the web sense) to carry over to Controlled Frame where it makes sense, and so calling it something based on that framing family of names aligns this work best with the web platform.

> Most other platforms also use the term webview: Android, Windows, Mac, iOS

Yes, WebView is available on a variety operating systems. The concept in those platforms is meant to refer to an interface that supports embedding a web page into an OS application, so it makes sense that operating systems providing similar functionality would reuse the WebView naming.
